FROM php:8.4-fpm-alpine AS builder

RUN apk add --no-cache \
    git curl bash zip unzip \
    libzip-dev icu-dev \
    && docker-php-ext-install pdo pdo_mysql zip intl opcache

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/backend

COPY composer.json composer.lock* ./
RUN composer install --no-dev --no-scripts --no-autoloader --prefer-dist

COPY . .
RUN composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction \
    && chmod +x bin/console

FROM php:8.4-fpm-alpine

RUN apk add --no-cache libzip icu-libs \
    && docker-php-ext-install pdo pdo_mysql zip intl opcache

COPY docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

WORKDIR /var/www/backend

COPY --from=builder /var/www/backend .

EXPOSE 9000
CMD ["php-fpm"]
